### ISSUE TITLE
在使用singleflight, 对缓存的设置应该在singleflight里

### ISSUE THREAD

**Issue by thinkgos** [chenyahui/gin-cache#1]
在使用singleflight, 对缓存的设置应该在singleflight里吧, 当高并发,发生shared同一个key的缓存值,重复设置store, 不知道你这redis能不能抗的住.
缓存应该只缓存成功的返回.毕竟你不知道下游业务是如何出错的,错误的返回不应该进行缓存.
另外对日志的调用,作为一个库,最好提供接口, 并给可选项配置,供使用者选择合适的日志组件.
结合你的库和官方的库,我也作为相应简化和适配. 刚好项目有用,所以也做了个库,[gin-cache](https://github.com/things-go/gin-cache)

**Comment by chenyahui** [comment]
@thinkgos 已修复，感谢反馈。另外，我也看了你的库，options的写法非常标准，值得学习~~
