### ISSUE TITLE
How to cache pages with specific HTTP status code?

### ISSUE THREAD

**Issue by rwv** [chenyahui/gin-cache#13]
I wonder the default strategy for `CacheByRequestPath`. Does it cache all HTTP status code or just `200`? Thank you!

**Comment by rwv** [comment]
I found this line in `Cache`
https://github.com/chenyahui/gin-cache/blob/eca3d49077068a0d69487898c62f71b5cd480356/cache.go#L102

Will `CacheByRequestPath` overwrite the default `Cache` strategy?

**Comment by chenyahui** [comment]
This cache middleware only handle success http response. If you want to cache other status, like 404/500, I can supply a new cache strategy

**Comment by rwv** [comment]
Thank you! I just want to make sure it only caches 2xx status. Maybe clarify this in README?

**Comment by chenyahui** [comment]
Ok, I will update readme.md later~

**Comment by victorboissiere** [comment]
I'm interested in the ability to cache 404. I'll see what I can do later on.
