### ISSUE TITLE
set设置值问题（类型）

### ISSUE THREAD

**Issue by ResistanceTo** [chenyahui/gin-cache#14]
现在设置值会通过一个序列化方法变成二进制值 [code](https://github.com/chenyahui/gin-cache/blob/c60dacc467bb6bdea961019c7796325c379c5d52/persist/redis.go#L25) 如果有需求是保存为字符串或者整型浮点型就不可用了，例如我要保存字符串asd，当前会保存为	\x0C\x00\x06asd。
我将原始函数改为SetByte现在满足需求，Set函数不做值类型的处理，是否还有其他好的实现方法。
```
func (store *RedisStore) Set(key string, value interface{}, expire time.Duration) error {
	ctx := context.TODO()
	return store.RedisClient.Set(ctx, key, value, expire).Err()
}
```

**Comment by chenyahui** [comment]
现在这个CacheStore.Set方案只是给gin-cache内部保存ResponseCache用的一套适配器，应该不会涉及非struct的序列化。

你这边用RedisStore的场景是什么？如果只是往里面set数据，可以直接调用RedisClient进行set，无需用persist.RedisStore

**Comment by ResistanceTo** [comment]
用来缓存token的，明白了，我应该使用redis的set方法。
