### ISSUE TITLE
Example for options

### ISSUE THREAD

**Issue by allesan** [chenyahui/gin-cache#18]
Can you please provide example in the documentation how to use hitCacheCallback?

**Comment by chenyahui** [comment]
ok, I'll provide an example later~

**Comment by chenyahui** [comment]
https://github.com/chenyahui/gin-cache/blob/main/examples/options/main.go 
I add an example for WithOnHitCache option, a common use case for WithOnHitCache is to record the number of hit caches.

**Comment by allesan** [comment]
Thanks!
