### ISSUE TITLE
Is there a way to invalidate cache?

### ISSUE THREAD

**Issue by habibrosyad** [chenyahui/gin-cache#2]
For example I put the cache middleware for a GET endpoint, but there's also a POST endpoint which supposed to be updating the results fetched from the GET endpoint. Therefore, whenever I call the POST endpoint, I would like whatever cache exists on the GET endpoint to be invalidated immediately so I could return the most up to date results.

Is there a way to accommodate this mechanism into gin-cache?

**Comment by chenyahui** [comment]
> For example I put the cache middleware for a GET endpoint, but there's also a POST endpoint which supposed to be updating the results fetched from the GET endpoint. Therefore, whenever I call the POST endpoint, I would like whatever cache exists on the GET endpoint to be invalidated immediately so I could return the most up to date results.
> 
> Is there a way to accommodate this mechanism into gin-cache?

@habibrosyad You can use `CacheStore.Delete` to invalidate cache.
