### ISSUE TITLE
Support go-redis/redis/v9 client

### ISSUE THREAD

**Issue by TeslaLyon** [chenyahui/gin-cache#20]
Cannot use 'global.App.Redis' (type *"github.com/go-redis/redis/v9".Client) as the type *"github.com/go-redis/redis/v8".Client

本地用的 v9 版本的包，发现您包里没有对应的。

**Comment by chenyahui** [comment]
新建了一个新的库，里面支持了redis v9 client

https://github.com/chenyahui/gin-cache-redis
