### ISSUE TITLE
Setting HTTP on hit or miss

### ISSUE THREAD

**Issue by allesan** [chenyahui/gin-cache#23]
Is there a way to set a http header on hit or miss?

**Comment by chenyahui** [comment]
You can use WithBeforeReplyWithCache option to custom response header.

https://github.com/chenyahui/gin-cache/blob/main/option.go#L94

**Comment by allesan** [comment]
I have this code

`var invalidateCache cache.Option = cache.WithBeforeReplyWithCache(func(c *gin.Context, cache *cache.ResponseCache) {
	c.Request.Header.Set("teest", "yes")
})`

But it doesn't set header

**Comment by chenyahui** [comment]
Maybe it should to use `c.Writer.Header`?

**Comment by allesan** [comment]
Thanks, it works like that!
