### ISSUE TITLE
[MemoryStore] Allow specifying max cache size to prevent OOM

### ISSUE THREAD

**Issue by huantt** [chenyahui/gin-cache#24]
In a production environment, caching data may keep growing so fast.
MemoryStore would allow specifying max cache size or at least max cache length (number of cache keys) then prune when it reaches

**Comment by chenyahui** [comment]
It is currently difficult to limit the overall memory, because the default ttlcache is implemented based on map. However, the total cached number can be limited

**Comment by allesan** [comment]
Can you give an example?

**Comment by huantt** [comment]
> Can you give an example?

My API serves a large number of products, I need to limit either size of cache or number of cache key to prevent OOM.

**Comment by chenyahui** [comment]
you can customize your own memory store according needs. refer to: https://github.com/chenyahui/gin-cache/blob/main/persist/memory.go

**Comment by chenyahui** [comment]
set WithCapacity option when new ttlcache

https://github.com/jellydator/ttlcache/blob/master/options.go#L35

**Comment by huantt** [comment]
> set WithCapacity option when new ttlcache, and use Cache funtion directly https://github.com/chenyahui/gin-cache/blob/main/cache.go#L34
> 
> https://github.com/jellydator/ttlcache/blob/master/options.go#L35

I got it.
Thank you!
