### ISSUE TITLE
Cache strategy based on some header

### ISSUE THREAD

**Issue by allesan** [chenyahui/gin-cache#27]
I would like to have different cache key based on the header that users set.
Is WithCacheStrategyByRequest() intended for this? I have trouble implementing this function. It looks like it's being overwritten in this lib.

This is my code 

`	var cacheStrategy cache.Option = cache.WithCacheStrategyByRequest(func(c *gin.Context) (bool, cache.Strategy) {
		var key string = "yes"

		if 1 < 2 {
			key = "no"
		}

		return true, cache.Strategy{
			CacheKey: key,
		}
	})
`

And I use it in CacheByRequestURI() but it never gets executed.

**Comment by chenyahui** [comment]
Do you mean expect not to cache data when 1<2? It should return `false,cache.Strategy{
		CacheKey: key,
	}`

**Comment by allesan** [comment]
No, I mean for cache key be different based on the header from the client.
Is that possible?

**Comment by allesan** [comment]
This is my example code

`	var cacheStrategy cache.Option = cache.WithCacheStrategyByRequest(func(c *gin.Context) (bool, cache.Strategy) {
		ua := c.GetHeader("User-Agent")

		client := strings.Contains(ua, "curl")

		var key string = "yes"

		if client {
			key = "no"	
		}

		return true, cache.Strategy{
			CacheKey: key,
		}
	})
`

**Comment by chenyahui** [comment]
it should use `Cache` function instead of `CacheByRequestURI` ,CacheByRequestURI will override the cache strategy.

**Comment by allesan** [comment]
Thanks, that is it.
