### ISSUE TITLE
Cache without cookie

### ISSUE THREAD

**Issue by cherimo** [chenyahui/gin-cache#28]
At the moment the cached content is also saved with Cookie/Session information witch is not ideal.
Is there a setting/option to cache only page content without headers or cookie info?

I want to go from this..
`;�� ResponseCache��StatusHeader��Data ��Header���������T����Content-Typeapplication/json; charset=utf-8 Set-Cookie�mysession=MTY3MTI5MTE2MXxOd3dBTkZCSFZFRlhVVTVDU1VkVVZVSkxTemMxVUVVMFRsaEtWMHhLVUZreVRrZEpTMFZIUVVOVVFVZFFOa2xNVFRSVFdGUkxOa0U9fN2Qa-r2Lgq8UVXWfYlU6PsWZv3uCDHNVI-EB7xfS3ld; Path=/; Expires=Sat, 17 Dec 2022 16:32:41 GMT; Max-Age=3600; Secure; SameSite=Strict{"count":10}
`

to this

`{"count":10}`

**Comment by chenyahui** [comment]
I push a new commit https://github.com/chenyahui/gin-cache/commit/7f8c3e5fd735bb6da275ee4a6b5c68127816318f , Does this meet your needs?

**Comment by cherimo** [comment]
@chenyahui Yes thank you very much, it looks much better now.

I use the following code:

`router.GET("/", cache.CacheByRequestPath(redisStore, 10*time.Second, cache.WithoutHeader()), getAlbums)`

This is the result:

```
;��
ResponseCache��StatusHeader��Data
��Header������������{"count":9}
```

So no cookie/session information stored anymore. 

Thanks, much appreciated.

**Comment by allesan** [comment]
Can you push a new version with this commit?

**Comment by chenyahui** [comment]
Done. https://github.com/chenyahui/gin-cache/releases/tag/v1.8.0
