### ISSUE TITLE
Cross-origin information is cached

### ISSUE THREAD

**Issue by nijinekoyo** [chenyahui/gin-cache#33]
When there are multiple cross-domain domain names that allow cross-domain information, it will cause confusion when the cross-domain information is cached. It is hoped that the cross-domain return header can be ignored during caching

**Comment by chenyahui** [comment]
@nijinekoyo Sorry for the delayed response. I have added a new option called "DiscardHeaders" and included "CorsHeaders" in the library. You can take a look at the commit to see if it meets your requirements. 
https://github.com/chenyahui/gin-cache/commit/a2f9e2bca718bcdcd0cf72e3dc4d057926bdb457

**Comment by nijinekoyo** [comment]
Wow, thank you so much for solving this problem

**Comment by chenyahui** [comment]
I released v1.9.0 for this feature. 

Just a reminder, please make sure to confirm if everything meets your expectations and conduct thorough testing before using it in a production environment.

https://github.com/chenyahui/gin-cache/blob/main/cache_test.go#L246

**Comment by nijinekoyo** [comment]
I successfully fixed the problem, thank you very much
