### ISSUE TITLE
关于Gin-Cache的一些疑问

### ISSUE THREAD

**Issue by AkimioJR** [chenyahui/gin-cache#43]
我有一个项目需要使用缓存，运行的大致逻辑是客户端向我写的web服务器获取数据，我的web服务器会请求上游的服务器，然后修改部分数据再返回，类似于一个middleware或者说warp
上游的数据库是sqlite，并不适合高并发，所以我想在我的程序部分做一个缓存优化一下
下面是几点疑问
1. 我看相关函数是CacheByRequestUri，请问缓存是近针对uri的吗，只要uri相同返回的数据就相同，不去判断查询参数和body
2. 缓存可以缓存类似于图片、音频、视频等文件吗，会将数据写入硬盘吗
3. 这个是另一个话题，和本项目无关，只是希望可以得到一些意见，因为上游使得用的是sqlite数据库，性能不好，我写的程序希望可以分布式部署的，所以想额外增加mariadb和redis进行缓存数据，需要缓存的数据大多是图片、音频等数据，不知道有没有一些开发建议

**感谢大佬解惑**

**Comment by chenyahui** [comment]
1. CacheByRequestUri相当于个shortcut函数。你这个需求可以通过直接调用Cache函数来解决
2. 目前只Cache了Body，如果你的图片视频是通过http body返回的，那是可以cache的。
3. 图片、音频一般适合放在object store上。例如腾讯云的cos之类的
